"""O(1) lookup over the SM x dtype x op optimal-selection table.

This is the *data* side of Tier-2 dispatch (see ``docs/OPTIMAL_SELECTION.md``):
the precomputed Cartesian table in ``providers/optimal.json`` (generated by
``scripts/gen_optimal.py``) materializing, per ``(logical_op, sm, dtype)``, the
optimal provider, whether it came from a real benchmark (``measured``) or the
curated baseline (``heuristic``), and a ``fallback_chain`` terminating in
``kernel-set``.

``select_optimal(logical_op, sm, dtype)`` is a **pure function** — a dictionary
lookup with graceful degradation:

    exact (op, sm, dtype) cell
        -> nearest feasible dtype for that (op, sm)
        -> the kernel-set terminal fallback

It loads the JSON **once** (cached at import-discovery time) and never imports
torch / CUDA / the kernel-set shared library, so it is safe to import on a no-GPU
host. The runtime dispatcher (``kernel_set.dispatch`` via ``backends._registry``)
consults this table as the single source of truth for its *ranking*; the
availability/arch probing still gates which ranked provider is actually runnable.
"""

from __future__ import annotations

import json
import os
from typing import Dict, List, Optional, Tuple

from ._probe import _SM_THRESHOLDS, canonical_sm

KERNEL_SET = "kernel-set"

# Repo layout: bindings/python/kernel_set/backends/optimal.py
#              -> providers/optimal.json  (../../../../providers/optimal.json)
_OPTIMAL_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "..", "..", "..", "providers", "optimal.json")

# Canonical alias map: dotted benchmark taxonomy -> dispatch logical_op id, so a
# caller may pass either ``"attention.prefill"`` or ``"attention_prefill"``.
_OP_ALIASES = {
    "attention.prefill": "attention_prefill",
    "attention.decode": "attention_decode",
    "norm.rmsnorm": "rmsnorm",
    "norm.fused_add_rmsnorm": "fused_add_rmsnorm",
    "rope.apply": "rope",
    "act.swiglu": "swiglu",
    "gemm.dense": "gemm",
    "loss.cross_entropy": "cross_entropy",
}

# dtype request -> canonical token used as the table key.
_DTYPE_ALIASES = {
    "float16": "fp16", "half": "fp16", "f16": "fp16", "fp16": "fp16",
    "bfloat16": "bf16", "bf16": "bf16",
    "float32": "fp32", "float": "fp32", "f32": "fp32", "tf32": "fp32",
    "fp32": "fp32",
    "float8_e4m3fn": "fp8", "float8_e4m3": "fp8", "fp8_e4m3": "fp8",
    "float8_e5m2": "fp8", "fp8_e5m2": "fp8", "fp8": "fp8",
    "int8": "int8", "i8": "int8", "w8a8": "int8",
    "int4": "int4", "i4": "int4", "w4a16": "int4", "awq": "int4",
    "gptq": "int4", "nf4": "int4",
    "fp4": "fp4", "nvfp4": "fp4", "mxfp4": "fp4",
}

# Preference order when the exact dtype is missing for an (op, sm): try the
# "nearest" compute dtype before giving up to kernel-set. fp16<->bf16 are
# interchangeable for most kernels; fp8 falls back to bf16; int* to bf16/fp16.
# NOTE: fp4 (NVFP4/MXFP4) is intentionally ABSENT here. fp4 is now WIRED, but
# only for the dedicated fp4 ops (nvfp4_gemm / mxfp4_gemm) and only on Blackwell
# (sm100+). For every OTHER op a fp4 request must resolve to the kernel-set
# fallback, NOT silently borrow the int4 cell — so fp4 has no nearest-dtype
# ladder. See docs/OPTIMAL_SELECTION.md / docs/QUANT_OPERATORS.md.
_DTYPE_NEAREST = {
    "fp16": ["fp16", "bf16", "fp32"],
    "bf16": ["bf16", "fp16", "fp32"],
    "fp32": ["fp32", "bf16", "fp16"],
    "fp8": ["fp8", "bf16", "fp16"],
    "int8": ["int8", "bf16", "fp16"],
    "int4": ["int4", "bf16", "fp16"],
}

# Capability-aware dtype gating, loaded from models/gpu_caps.json through
# _probe.py so the pure selector, runtime dispatch, and generator share one
# source of truth. dtypes absent here (fp16/fp32/int8/int4) have no arch gate.
_DTYPE_CAP_KEY = {
    "bf16": "bf16",
    "tf32": "tf32",
    "fp8": "fp8",
    "fp4": "fp4",
}


def _dtype_feasible(sm: Optional[int], req: Optional[str]) -> bool:
    """Is the requested (normalized) dtype supported by ``sm``? An infeasible
    request (e.g. fp8 on sm75, bf16 on sm75, fp4 on sm<100) must NOT be served by
    a nearest-dtype cell — it resolves straight to the kernel-set fallback so
    runtime dispatch never gates an installed provider against the original
    (infeasible) dtype."""
    cap = _DTYPE_CAP_KEY.get(req)
    min_sm = _SM_THRESHOLDS.get(cap) if cap else None
    if min_sm is None or sm is None:
        return True
    return int(sm) >= int(min_sm)


def _normalize_op(logical_op: str) -> str:
    return _OP_ALIASES.get(logical_op, logical_op)


def _normalize_dtype(dtype) -> Optional[str]:
    if dtype is None:
        return None
    name = str(getattr(dtype, "name", dtype))
    name = name.replace("torch.", "").strip().lower()
    return _DTYPE_ALIASES.get(name, name if name else None)


# --------------------------------------------------------------------------- #
# Load + index the table once. Never raises: a missing/malformed file yields an
# empty index (every lookup then gracefully resolves to the kernel-set fallback).
# --------------------------------------------------------------------------- #
def _load() -> Tuple[Dict[Tuple[str, int, str], dict],
                     Dict[Tuple[str, int], List[str]], dict]:
    cells_by_key: Dict[Tuple[str, int, str], dict] = {}
    dtypes_by_op_sm: Dict[Tuple[str, int], List[str]] = {}
    meta: dict = {}
    try:
        with open(_OPTIMAL_PATH) as f:
            doc = json.load(f)
        meta = {k: doc[k] for k in ("schema_version", "fill_rule", "stats")
                if k in doc}
        for c in doc.get("cells", []):
            key = (c["logical_op"], int(c["sm"]), c["dtype"])
            cells_by_key[key] = c
            dtypes_by_op_sm.setdefault(
                (c["logical_op"], int(c["sm"])), []).append(c["dtype"])
    except Exception:
        pass
    return cells_by_key, dtypes_by_op_sm, meta


_CELLS, _DTYPES_BY_OP_SM, _META = _load()


def reload_table() -> None:
    """Re-read providers/optimal.json (e.g. after regenerating it). Mainly for
    tests; the table is otherwise loaded once at import."""
    global _CELLS, _DTYPES_BY_OP_SM, _META
    _CELLS, _DTYPES_BY_OP_SM, _META = _load()


# --------------------------------------------------------------------------- #
# The pure selector.
# --------------------------------------------------------------------------- #
def _ks_cell(logical_op: str, sm: Optional[int], dtype) -> dict:
    """The graceful terminal: kernel-set, source 'fallback', chain [kernel-set]."""
    return {
        "logical_op": logical_op,
        "sm": sm,
        "dtype": _normalize_dtype(dtype),
        "provider": KERNEL_SET,
        "source": "fallback",
        "fallback_chain": [KERNEL_SET],
    }


def select_optimal(logical_op: str, sm, dtype) -> dict:
    """Return ``{provider, source, fallback_chain}`` (plus ``logical_op``, ``sm``,
    ``dtype`` and, for measured cells, ``metric``/``gpu``) for the requested
    ``(logical_op, sm, dtype)`` via an O(1) Cartesian-table lookup.

    Graceful fallback ladder:

    0. **capability gate** — if the requested dtype is arch-infeasible for this
       ``sm`` (fp8 on sm<89, bf16 on sm<80, fp4 on sm<100), return the kernel-set
       fallback IMMEDIATELY. We never nearest-dtype-fall an infeasible request
       into a different-dtype cell (which would let dispatch gate an installed
       provider against the original, infeasible dtype — the HIGH bug from the
       review).
    1. **exact cell** ``(op, sm, dtype)`` — measured winner if one exists, else
       the heuristic baseline;
    2. **nearest feasible dtype** for that ``(op, sm)`` — e.g. an fp16 request on
       a cell that only has bf16 resolves to the bf16 cell;
    3. **kernel-set** — the portable terminal fallback (``source='fallback'``,
       chain ``['kernel-set']``) when nothing feasible exists (unknown op, an
       arch with no table row, or dtype-infeasible like fp8 on sm75).

    Pure: no torch/CUDA import, no global mutation. The returned dict is a fresh
    copy (safe for the caller to mutate)."""
    op = _normalize_op(logical_op)
    req = _normalize_dtype(dtype)
    sm_int: Optional[int] = None
    try:
        sm_int = canonical_sm(int(sm)) if sm is not None else None
    except (TypeError, ValueError):
        sm_int = None

    # 0) capability gate: an arch-infeasible dtype goes straight to kernel-set.
    if sm_int is not None and req is not None and \
            not _dtype_feasible(sm_int, req):
        return _ks_cell(op, sm_int, dtype)

    if sm_int is not None and req is not None:
        # 1) exact cell.
        cell = _CELLS.get((op, sm_int, req))
        if cell is not None:
            return dict(cell)
        # 2) nearest feasible dtype for this (op, sm).
        available = _DTYPES_BY_OP_SM.get((op, sm_int), [])
        for cand in _DTYPE_NEAREST.get(req, [req]):
            if cand in available:
                return dict(_CELLS[(op, sm_int, cand)])
    elif sm_int is not None and req is None:
        # No dtype constraint: pick a deterministic representative cell for the
        # (op, sm) — prefer bf16, then fp16, then whatever the row offers.
        available = _DTYPES_BY_OP_SM.get((op, sm_int), [])
        for cand in ("bf16", "fp16", "fp32", "fp8", "int8", "int4", "fp4"):
            if cand in available:
                return dict(_CELLS[(op, sm_int, cand)])
        if available:
            return dict(_CELLS[(op, sm_int, available[0])])

    # 3) terminal fallback.
    return _ks_cell(op, sm_int, dtype)


def optimal_chain(logical_op: str, sm, dtype) -> List[str]:
    """Convenience: just the fallback chain (provider ids, ending kernel-set)."""
    return list(select_optimal(logical_op, sm, dtype)["fallback_chain"])


def table_meta() -> dict:
    """Schema/stats metadata for the loaded table (empty if the file is absent)."""
    return dict(_META)


def has_table() -> bool:
    """True if providers/optimal.json was found & parsed (non-empty index)."""
    return bool(_CELLS)
