#!/usr/bin/env python3
"""kernel-set auto-selection engine (pure stdlib).

Given a (model, gpu, dtype, mode) request, this module decides — per logical op
— the STRONGEST kernel-set C ABI entry point plus the dtype / quantization
scheme to feed it, and a one-line rationale.

Design:
  * registry.json (machine-readable, generated by _gen_registry.py) supplies the
    architecture facts and the *default* op->fn map per model.
  * This engine layers GPU-capability + dtype rules on top of those facts:
      - FP8 e4m3 only on sm89+ (L4, RTX4090) and sm90 (H100); A100/T4/A10 fall
        back to bf16 (A100/A10) or fp16 (T4).
      - W4A16 (AWQ/GPTQ int4) is always available (sm75+); chosen kernel is the
        same ABI symbol everywhere (ks_gemm_w4a16) but the rationale names the
        real-world best-in-class backend (Machete on sm90, Marlin on sm80/89).
      - W8A8 int8 available on sm75+ (ks_gemm_w8a8).
      - MLA models route decode to ks_mla_decode; MoE models add the gate +
        grouped-GEMM ops; GQA/MQA decode uses paged attention with kv grouping.
      - bf16 needs sm80+; on T4 (sm75) we degrade bf16 -> fp16.

No third-party imports. Importable (functions return dicts) and runnable.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY_PATH = os.path.join(HERE, "registry.json")


# ---------------------------------------------------------------------------
# GPU capability table.
#   sm: compute capability (major*10+minor)
#   fp8: e4m3/e5m2 tensor cores
#   bf16/tf32: native tensor-core support
#   fp4: mxfp4/nvfp4 (Blackwell)
# ---------------------------------------------------------------------------
GPUS = {
    "a100":    {"name": "NVIDIA A100",  "sm": 80, "arch": "Ampere",
                "fp8": False, "bf16": True,  "tf32": True,  "int8": True,
                "int4": True, "fp4": False, "wgmma": False},
    "l4":      {"name": "NVIDIA L4",    "sm": 89, "arch": "Ada",
                "fp8": True,  "bf16": True,  "tf32": True,  "int8": True,
                "int4": True, "fp4": False, "wgmma": False},
    "h100":    {"name": "NVIDIA H100",  "sm": 90, "arch": "Hopper",
                "fp8": True,  "bf16": True,  "tf32": True,  "int8": True,
                "int4": True, "fp4": False, "wgmma": True},
    "t4":      {"name": "NVIDIA T4",    "sm": 75, "arch": "Turing",
                "fp8": False, "bf16": False, "tf32": False, "int8": True,
                "int4": True, "fp4": False, "wgmma": False},
    "a10":     {"name": "NVIDIA A10",   "sm": 86, "arch": "Ampere",
                "fp8": False, "bf16": True,  "tf32": True,  "int8": True,
                "int4": True, "fp4": False, "wgmma": False},
    "rtx4090": {"name": "NVIDIA RTX 4090", "sm": 89, "arch": "Ada",
                "fp8": True,  "bf16": True,  "tf32": True,  "int8": True,
                "int4": True, "fp4": False, "wgmma": True},
}

# Aliases people actually type.
GPU_ALIASES = {
    "a100-80gb": "a100", "a100-40gb": "a100", "a800": "a100",
    "h800": "h100", "h200": "h100", "hopper": "h100",
    "l4": "l4", "ada": "l4",
    "4090": "rtx4090", "rtx-4090": "rtx4090",
    "a10g": "a10",
}

# Requested dtype vocabulary.
DTYPES = {"bf16", "fp16", "f16", "fp8", "fp8_e4m3", "fp8_e5m2",
          "w4a16", "int4", "awq", "gptq", "w8a8", "int8", "mxfp4", "fp4",
          "tf32", "f32", "fp32", "auto"}

DTYPE_NORMALIZE = {
    "f16": "fp16", "fp8_e4m3": "fp8", "fp8_e5m2": "fp8_e5m2",
    "int4": "w4a16", "awq": "w4a16", "gptq": "w4a16",
    "int8": "w8a8", "fp32": "f32", "fp4": "mxfp4",
}

# ks_dtype_t enum tokens (compute dtype actually handed to the kernel).
KS_DTYPE = {
    "bf16": "KS_DTYPE_BF16",
    "fp16": "KS_DTYPE_F16",
    "f32": "KS_DTYPE_F32",
    "tf32": "KS_DTYPE_F32",        # TF32 is the F32 path on tensor cores
    "fp8": "KS_DTYPE_F8E4M3",
    "fp8_e5m2": "KS_DTYPE_F8E5M2",
    "w4a16": "KS_DTYPE_F16",       # activations fp16/bf16; weights packed I4
    "w8a8": "KS_DTYPE_I8",
    "mxfp4": "KS_DTYPE_F8E4M3",    # modeled as fp8 compute (no native fp4 ABI)
}


class SelectionError(Exception):
    pass


def load_registry(path=REGISTRY_PATH):
    with open(path) as f:
        return json.load(f)


def list_models(reg):
    return [m["id"] for m in reg["models"]]


def find_model(reg, model_id):
    mid = model_id.strip().lower()
    for m in reg["models"]:
        if m["id"] == mid:
            return m
    # tolerant match: allow family display name or example name
    for m in reg["models"]:
        if m["family"].lower() == mid:
            return m
        for ex in m.get("examples", []):
            if ex.lower() == mid:
                return m
    raise SelectionError(
        f"unknown model '{model_id}'. Try one of: {', '.join(list_models(reg))}")


def resolve_gpu(gpu):
    g = gpu.strip().lower()
    g = GPU_ALIASES.get(g, g)
    if g not in GPUS:
        raise SelectionError(
            f"unknown gpu '{gpu}'. Known: {', '.join(GPUS)}")
    return g, GPUS[g]


def normalize_dtype(dtype):
    d = dtype.strip().lower()
    if d not in DTYPES:
        raise SelectionError(
            f"unknown dtype '{dtype}'. Known: {', '.join(sorted(DTYPES))}")
    return DTYPE_NORMALIZE.get(d, d)


# ---------------------------------------------------------------------------
# Compute-dtype resolution: take the *requested* dtype and what the model
# supports, and degrade to the strongest dtype the GPU can actually run.
# Returns (resolved_scheme, note).
# ---------------------------------------------------------------------------
def resolve_compute_dtype(requested, gpu_caps, model):
    supported = set(model["arch"].get("quant", []))
    # "auto": pick the best the model+gpu allow. Prefer fp8 on capable HW for
    # large models, else bf16, else fp16.
    if requested == "auto":
        if "fp8" in supported and gpu_caps["fp8"]:
            return "fp8", "auto: model has FP8 weights and GPU has FP8 tensor cores"
        if gpu_caps["bf16"]:
            return "bf16", "auto: bf16 (broadest tensor-core dtype on this GPU)"
        return "fp16", "auto: fp16 (GPU predates bf16 tensor cores)"

    note = None
    d = requested

    # fp8 family: needs sm89+ tensor cores; else degrade.
    if d in ("fp8", "fp8_e5m2"):
        if not gpu_caps["fp8"]:
            fallback = "bf16" if gpu_caps["bf16"] else "fp16"
            note = (f"FP8 requested but {gpu_caps['name']} (sm{gpu_caps['sm']}) "
                    f"has no FP8 tensor cores -> degrade to {fallback}")
            return fallback, note

    # mxfp4 / fp4: no native FP4 ABI here and only Blackwell has FP4 TCs;
    # model the experts as fp8 on fp8-capable HW, else bf16.
    if d == "mxfp4":
        if gpu_caps["fp8"]:
            return "fp8", ("MXFP4 experts modeled via FP8 compute path "
                           "(no native FP4 on this GPU)")
        fallback = "bf16" if gpu_caps["bf16"] else "fp16"
        return fallback, f"MXFP4 unsupported on sm{gpu_caps['sm']} -> {fallback}"

    # bf16 needs sm80+; T4 degrades to fp16.
    if d == "bf16" and not gpu_caps["bf16"]:
        return "fp16", (f"bf16 requested but sm{gpu_caps['sm']} lacks bf16 "
                        f"tensor cores -> fp16")

    # tf32 is only an Ampere+ F32 path.
    if d == "tf32" and not gpu_caps["tf32"]:
        return "fp16", f"tf32 unsupported on sm{gpu_caps['sm']} -> fp16"

    # w4a16 / w8a8 always OK on sm75+ (all our GPUs).
    return d, note


# Real-world best-in-class backend names for the rationale (the ABI symbol is
# the same; this just names *why* it's strongest on that arch/dtype).
def gemm_backend_name(scheme, gpu_caps):
    sm = gpu_caps["sm"]
    if scheme == "fp8":
        return "DeepGEMM" if sm >= 90 else "TransformerEngine/cuBLASLt FP8"
    if scheme == "w4a16":
        return "Machete (WGMMA)" if sm >= 90 else "Marlin"
    if scheme == "w8a8":
        return "CUTLASS INT8 (SmoothQuant)"
    if scheme in ("bf16", "fp16"):
        return "cuBLASLt / CUTLASS"
    if scheme in ("tf32", "f32"):
        return "CUTLASS TF32"
    return "cuBLASLt"


def attn_backend_name(gpu_caps, mla=False, decode=False):
    sm = gpu_caps["sm"]
    if mla:
        return "FlashMLA" if sm >= 90 else "FlashInfer MLA"
    if decode:
        return "FlashInfer paged decode"
    return "FlashAttention-3" if sm >= 90 else "FlashAttention-2"


# Which logical ops are GEMM-shaped (so they honor the weight-quant scheme).
GEMM_OPS = {"qkv_proj", "o_proj", "mlp_gate_up", "mlp_down", "lm_head",
            "moe_grouped_gemm"}
# Ops that always stay in the model's activation dtype (norms, rope, act, etc).
ACT_DTYPE_OPS = {"attn_norm", "ffn_norm", "rope", "mlp_act", "embedding",
                 "attn_prefill", "attn_decode", "attn_backward"}


def _pick_gemm_fn(op, scheme, default_fn):
    """Choose the quant-aware GEMM ABI symbol for a GEMM-shaped op."""
    if op == "moe_grouped_gemm":
        # grouped path has a single ABI symbol; dtype carries the quant info
        return "ks_moe_grouped_gemm"
    if scheme == "w4a16":
        return "ks_gemm_w4a16"
    if scheme == "w8a8":
        return "ks_gemm_w8a8"
    # fp8/bf16/fp16/tf32 dense GEMM. Use the bias+act fused epilogue for the
    # gate/up MLP projection (fuses SwiGLU's act when packed); plain ks_gemm
    # for the rest. We keep ks_gemm as the canonical symbol so the table stays
    # readable, but record fused availability in the note.
    return default_fn if default_fn else "ks_gemm"


def select(model_id, gpu, dtype, mode="inference", reg=None):
    """Return the full per-op plan dict."""
    reg = reg or load_registry()
    model = find_model(reg, model_id)
    gkey, gcaps = resolve_gpu(gpu)
    requested = normalize_dtype(dtype)
    scheme, dnote = resolve_compute_dtype(requested, gcaps, model)

    arch = model["arch"]
    is_mla = arch["attention"] == "MLA"
    is_moe = arch["mlp"]["type"] == "MoE"
    attn = arch["attention"]
    act_ks_dtype = KS_DTYPE.get(
        "bf16" if scheme in ("w4a16", "w8a8", "fp8", "fp8_e5m2", "mxfp4")
        and gcaps["bf16"] else
        ("fp16" if scheme in ("w4a16", "w8a8", "fp8", "fp8_e5m2", "mxfp4")
         else scheme), "KS_DTYPE_BF16")
    gemm_ks_dtype = KS_DTYPE.get(scheme, "KS_DTYPE_BF16")

    ops = list(reg["logical_ops"])
    if mode == "training":
        # Training is forward-prefill + backward; decode-time ops don't apply.
        ops = [o for o in ops if o not in ("attn_decode", "sampling")]
        ops = ops + list(reg["training_ops"])

    plan = {}
    base_ops = model["ops"]

    for op in ops:
        entry = build_op(op, model, base_ops, scheme, gcaps,
                         act_ks_dtype, gemm_ks_dtype, is_mla, is_moe, attn, mode)
        if entry is not None:
            plan[op] = entry

    return {
        "model": model["id"],
        "family": model["family"],
        "gpu": gcaps["name"],
        "gpu_key": gkey,
        "sm": gcaps["sm"],
        "arch_summary": arch_summary(arch),
        "requested_dtype": dtype,
        "resolved_scheme": scheme,
        "dtype_note": dnote,
        "mode": mode,
        "ops": plan,
    }


def build_op(op, model, base_ops, scheme, gcaps, act_dt, gemm_dt,
             is_mla, is_moe, attn, mode):
    sm = gcaps["sm"]

    # --- training-only ops -------------------------------------------------
    if op == "attn_backward":
        return mk("ks_flash_attn_backward", act_dt,
                  f"{attn_backend_name(gcaps)} backward (training)")
    if op == "cross_entropy":
        return mk("ks_fused_linear_cross_entropy", "KS_DTYPE_F32",
                  "Liger-style chunked fused-linear-CE (no full-logit materialization)")
    if op == "optimizer":
        return mk("ks_adamw", "KS_DTYPE_F32",
                  "Apex-style fused AdamW; fp32 master weights + state")

    # --- ops that don't exist for this model ------------------------------
    spec = base_ops.get(op)
    if spec is None:
        # moe_* ops only present for MoE models; mlp dense ops still apply.
        return None

    fn = spec["fn"]

    # ---- attention -------------------------------------------------------
    if op == "attn_prefill":
        # MLA prefill still uses flash on up-projected q/k/v.
        return mk("ks_flash_attn_varlen", act_dt,
                  f"{attn_backend_name(gcaps)} varlen prefill"
                  + (" (FP8 path)" if scheme in ("fp8",) and sm >= 90 else "")
                  + grouping_note(model["arch"]))
    if op == "attn_decode":
        if is_mla:
            return mk("ks_mla_decode", act_dt,
                      f"{attn_backend_name(gcaps, mla=True)} over compressed "
                      f"latent KV (rank "
                      f"{kv_lora(model)})")
        return mk("ks_paged_attn_decode", act_dt,
                  f"{attn_backend_name(gcaps, decode=True)}"
                  + grouping_note(model["arch"]))

    # ---- norms -----------------------------------------------------------
    if op in ("attn_norm", "ffn_norm"):
        if fn == "ks_layer_norm":
            return mk("ks_layer_norm", act_dt,
                      "LayerNorm (fp32 accumulate)")
        # RMSNorm: prefer the fused add-residual variant between sublayers.
        backend = "Liger" if mode == "training" else "FlashInfer/vLLM"
        return mk("ks_rms_norm_residual", act_dt,
                  f"{backend} fused add-RMSNorm")

    # ---- rope ------------------------------------------------------------
    if op == "rope":
        interleaved = (model["arch"].get("rope") or {}).get("style") == "gptj"
        conv = "GPT-J interleaved" if interleaved else "NeoX rotate-half"
        rscale = (model["arch"].get("rope") or {}).get("scaling")
        sc = f", {rscale} scaling" if rscale else ""
        return mk("ks_rope_gather", act_dt,
                  f"{conv} RoPE{sc} (fp32 angle math)")

    # ---- embedding / sampling -------------------------------------------
    if op == "embedding":
        return mk("ks_embedding_lookup", act_dt, "embedding gather")
    if op == "sampling":
        return mk("ks_sample", "KS_DTYPE_F32",
                  "FlashInfer-style fused temp+top-k+top-p sampling")

    # ---- MoE gate --------------------------------------------------------
    if op == "moe_gate":
        if fn == "ks_moe_gate_sigmoid_group_topk":
            mlp = model["arch"]["mlp"]
            return mk("ks_moe_gate_sigmoid_group_topk", "KS_DTYPE_F32",
                      f"DeepSeek group-limited aux-loss-free sigmoid gating "
                      f"(top-{mlp.get('top_k')} of {mlp.get('n_experts')}, "
                      f"{mlp.get('n_group')} groups)")
        mlp = model["arch"]["mlp"]
        return mk("ks_moe_gate_softmax_topk", "KS_DTYPE_F32",
                  f"softmax top-{mlp.get('top_k')} of {mlp.get('n_experts')} routing")

    # ---- MoE grouped gemm ------------------------------------------------
    if op == "moe_grouped_gemm":
        be = gemm_backend_name(scheme, gcaps)
        if scheme == "fp8" and sm >= 90:
            be = "DeepGEMM grouped (FP8 block-scaled)"
        elif scheme == "fp8":
            be = "CUTLASS grouped FP8"
        elif scheme in ("bf16", "fp16"):
            be = "Triton fused_moe / CUTLASS grouped"
        return mk("ks_moe_grouped_gemm", gemm_dt,
                  f"{be}; expert weights {scheme}")

    # ---- MLP activation --------------------------------------------------
    if op == "mlp_act":
        if fn == "ks_geglu":
            return mk("ks_geglu", act_dt, "GeGLU (gelu-tanh) gated act")
        if fn == "ks_gelu":
            return mk("ks_gelu", act_dt, "dense GeLU MLP activation")
        be = "Liger" if mode == "training" else "vLLM SiLU-mul"
        fused = (" (fused GEMM+SwiGLU on Hopper FP8)"
                 if scheme == "fp8" and sm >= 90 else "")
        return mk("ks_swiglu", act_dt, f"{be} SwiGLU{fused}")

    # ---- GEMM-shaped ops (qkv/o/gate_up/down/lm_head) -------------------
    if op in GEMM_OPS:
        chosen = _pick_gemm_fn(op, scheme, fn)
        be = gemm_backend_name(scheme, gcaps)
        extra = ""
        if op == "lm_head":
            extra = " (final logits)"
        if op == "mlp_gate_up" and not is_moe:
            extra = " (gate+up; fuse act via ks_gemm_bias_act)"
        return mk(chosen, gemm_dt, f"{be} {scheme} GEMM{extra}")

    # default passthrough
    return mk(fn, act_dt, "")


def mk(fn, ks_dtype, rationale):
    return {"fn": fn, "ks_dtype": ks_dtype, "rationale": rationale}


def grouping_note(arch):
    a = arch["attention"]
    if a == "GQA":
        return f" (GQA: {arch['n_kv_heads']} kv-heads shared by {arch['n_heads']} q-heads)"
    if a == "MQA":
        return f" (MQA: 1 kv-group)"
    if a == "MLA":
        return " (MLA latent KV)"
    return " (MHA)"


def kv_lora(model):
    for e in model["arch"].get("extras", []):
        if e.startswith("kv-lora-rank-"):
            return e.rsplit("-", 1)[-1]
    return "512"


def arch_summary(arch):
    mlp = arch["mlp"]
    if mlp["type"] == "MoE":
        mlp_str = (f"MoE {mlp.get('n_experts')}e/top-{mlp.get('top_k')}"
                   + (f"+{mlp['n_shared']}shared" if mlp.get("n_shared") else "")
                   + f" {mlp.get('gating', 'softmax')}")
    else:
        mlp_str = mlp["type"]
    r = arch.get("rope")
    if r is None:
        rope_str = "ALiBi/none"
    else:
        rope_str = f"{r['style']} theta={r['theta']}"
        if r.get("scaling"):
            rope_str += f"/{r['scaling']}"
    return {
        "attention": arch["attention"],
        "heads": arch["n_heads"],
        "kv_heads": arch["n_kv_heads"],
        "head_dim": arch["head_dim"],
        "hidden": arch["hidden"],
        "vocab": arch["vocab"],
        "norm": arch["norm"],
        "rope": rope_str,
        "mlp": mlp_str,
        "quant": ",".join(arch.get("quant", [])),
    }


if __name__ == "__main__":
    # Smoke test when run directly.
    reg = load_registry()
    for (m, g, d, mode) in [
        ("deepseek-v3", "h100", "fp8", "inference"),
        ("llama-3-8b", "a100", "bf16", "inference"),
        ("mixtral-8x7b", "l4", "w4a16", "inference"),
        ("gemma2-9b", "t4", "bf16", "inference"),
        ("llama-3-70b", "h100", "bf16", "training"),
    ]:
        p = select(m, g, d, mode, reg)
        print(f"\n== {m} on {g} ({d}, {mode}) -> scheme={p['resolved_scheme']}")
        for op, e in p["ops"].items():
            print(f"  {op:18s} {e['fn']:28s} {e['ks_dtype']:16s} {e['rationale']}")
