#!/usr/bin/env python3
"""kernel-set auto-selection engine (pure stdlib).

Given a (model, gpu, dtype, mode) request, this module decides — per logical op
— the STRONGEST kernel-set C ABI entry point plus the dtype / quantization
scheme to feed it, and a one-line rationale.

Design:
  * registry.json (machine-readable, generated by _gen_registry.py) supplies the
    architecture facts and the *default* op->fn map per model.
  * This engine layers GPU-capability + dtype rules on top of those facts:
      - FP8 e4m3 only on sm89+ (L4, RTX4090) and sm90 (H100); A100/T4/A10 fall
        back to bf16 (A100/A10) or fp16 (T4).
      - W4A16 (AWQ/GPTQ int4) is always available (sm75+); chosen kernel is the
        same ABI symbol everywhere (ks_gemm_w4a16) but the rationale names the
        real-world best-in-class backend (Machete on sm90, Marlin on sm80/89).
      - W8A8 int8 available on sm75+ (ks_gemm_w8a8).
      - MLA models route decode to ks_mla_decode; MoE models add the gate +
        grouped-GEMM ops; GQA/MQA decode uses paged attention with kv grouping.
      - bf16 needs sm80+; on T4 (sm75) we degrade bf16 -> fp16.

No third-party imports. Importable (functions return dicts) and runnable.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY_PATH = os.path.join(HERE, "registry.json")
GPU_CAPS_PATH = os.path.join(HERE, "gpu_caps.json")


# ---------------------------------------------------------------------------
# GPU capability + dtype tables.
#   Single source of truth lives in models/gpu_caps.json (shared with the
#   dispatch probe in bindings/.../backends/_probe.py). We load it here and
#   reconstruct the public symbols this module has always exposed:
#     GPUS  {gpu: {name, sm, arch, fp8, bf16, tf32, int8, int4, fp4, wgmma}}
#     GPU_ALIASES {alias: canonical}
#     DTYPES / DTYPE_NORMALIZE / KS_DTYPE
#   sm: compute capability (major*10+minor); fp8: e4m3/e5m2 tensor cores;
#   bf16/tf32: native tensor-core support; fp4: mxfp4/nvfp4 (Blackwell).
# ---------------------------------------------------------------------------
def _load_gpu_caps(path=GPU_CAPS_PATH):
    with open(path) as f:
        return json.load(f)


_CAPS = _load_gpu_caps()

GPUS = {}
GPU_ALIASES = {}
for _gid, _g in _CAPS["gpus"].items():
    entry = {"name": _g["name"], "sm": _g["sm"], "arch": _g["arch"]}
    entry.update(_g["caps"])
    GPUS[_gid] = entry
    for _alias in _g.get("aliases", []):
        GPU_ALIASES[_alias] = _gid

# Requested dtype vocabulary + normalization (-> internal scheme tokens).
DTYPES = set(_CAPS["ksctl_dtypes"])
DTYPE_NORMALIZE = {k: v for k, v in _CAPS["ksctl_dtype_normalize"].items()
                   if not k.startswith("_")}
# ks_dtype_t enum tokens (compute dtype actually handed to the kernel).
KS_DTYPE = {k: v for k, v in _CAPS["ks_dtype_enum"].items()
            if not k.startswith("_")}
# Named SM thresholds (FP8=89, BF16/TF32=80, ...) — available for callers that
# want the magic numbers by name instead of hardcoding `sm >= 90` etc.
SM_THRESHOLDS = {k: v for k, v in _CAPS["sm_thresholds"].items()
                 if not k.startswith("_")}
SM_FAMILY_ALIASES = {int(k): int(v) for k, v in
                     _CAPS.get("sm_family_aliases", {}).items()
                     if not k.startswith("_")}


class SelectionError(Exception):
    pass


# ---------------------------------------------------------------------------
# Consume the Cartesian optimal-selection table (providers/optimal.json,
# generated by scripts/gen_optimal.py). This is the single source of truth for
# the *industry-best external provider* per (logical_op, sm, dtype). The planner
# annotates each op's plan entry with that provider + whether it is a measured
# benchmark winner or a heuristic baseline, so `ksctl plan` shows the optimal
# runtime backend alongside the kernel-set C-ABI fallback. Pure stdlib; never
# raises (a missing/malformed table just means no annotation).
# ---------------------------------------------------------------------------
_OPTIMAL_PATH = os.path.join(os.path.dirname(HERE), "providers", "optimal.json")

# Map the planner's logical op ids -> optimal-table logical_op ids.
_PLAN_OP_TO_OPTIMAL = {
    "attn_norm": "rmsnorm",
    "ffn_norm": "rmsnorm",
    "rope": "rope",
    "attn_prefill": "attention_prefill",
    "attn_decode": "attention_decode",
    "qkv_proj": "gemm",
    "o_proj": "gemm",
    "mlp_gate_up": "gemm",
    "mlp_down": "gemm",
    "lm_head": "gemm",
    "mlp_act": "swiglu",
    "moe_gate": "moe_gate",
    "moe_grouped_gemm": "moe",
    "ssm": "selective_scan",
    "conv1d": "causal_conv1d",
    "cross_entropy": "cross_entropy",
}

# Planner scheme token -> optimal-table dtype key.
_SCHEME_TO_DTYPE = {
    "bf16": "bf16", "fp16": "fp16", "fp32": "fp32", "tf32": "fp32",
    "fp8": "fp8", "fp8_e5m2": "fp8",
    "w8a8": "int8", "w4a16": "int4", "mxfp4": "fp4",
}

# dtype-preference ladder for a graceful nearest-dtype lookup (mirrors the
# binding-side selector so the planner and runtime agree). fp4 is intentionally
# absent (no NVFP4 cell / runtime adapter): an fp4 scheme has no optimal-table
# annotation rather than silently borrowing the int4 cell. In practice the
# planner degrades mxfp4 -> fp8/bf16 in resolve_compute_dtype before this lookup.
_DTYPE_NEAREST = {
    "fp16": ["fp16", "bf16", "fp32"], "bf16": ["bf16", "fp16", "fp32"],
    "fp32": ["fp32", "bf16", "fp16"], "fp8": ["fp8", "bf16", "fp16"],
    "int8": ["int8", "bf16", "fp16"], "int4": ["int4", "bf16", "fp16"],
}


def _load_optimal_table(path=_OPTIMAL_PATH):
    """{(logical_op, sm, dtype): cell} index, or {} if the file is absent."""
    try:
        with open(path) as f:
            doc = json.load(f)
    except Exception:
        return {}, {}
    by_key = {}
    dtypes_by_op_sm = {}
    for c in doc.get("cells", []):
        by_key[(c["logical_op"], int(c["sm"]), c["dtype"])] = c
        dtypes_by_op_sm.setdefault((c["logical_op"], int(c["sm"])), []).append(
            c["dtype"])
    return by_key, dtypes_by_op_sm


_OPTIMAL_TABLE, _OPTIMAL_DTYPES = _load_optimal_table()


def _optimal_table_sm(sm):
    sm_int = int(sm)
    return SM_FAMILY_ALIASES.get(sm_int, sm_int)


def optimal_lookup_op(plan_op, scheme):
    """Planner op -> optimal-table op, accounting for quantized GEMM schemes."""
    if plan_op in GEMM_OPS and scheme == "mxfp4":
        return "mxfp4_gemm"
    if plan_op in DENSE_GEMM_OPS:
        if scheme == "fp8":
            return "fp8_gemm"
        if scheme == "w8a8":
            return "int8_gemm"
        if scheme == "w4a16":
            return "w4a16"
    return _PLAN_OP_TO_OPTIMAL.get(plan_op)


def optimal_cell(plan_op, sm, scheme):
    """Look up the optimal-table cell for a planner (op, sm, scheme), with a
    graceful nearest-dtype fallback. Returns the cell dict or None."""
    op = optimal_lookup_op(plan_op, scheme)
    if op is None:
        return None
    dtype = _SCHEME_TO_DTYPE.get(scheme, scheme)
    sm_key = _optimal_table_sm(sm)
    cell = _OPTIMAL_TABLE.get((op, sm_key, dtype))
    if cell is not None:
        return cell
    avail = _OPTIMAL_DTYPES.get((op, sm_key), [])
    for cand in _DTYPE_NEAREST.get(dtype, [dtype]):
        if cand in avail:
            return _OPTIMAL_TABLE.get((op, sm_key, cand))
    return None


def load_registry(path=REGISTRY_PATH):
    with open(path) as f:
        return json.load(f)


def list_models(reg):
    return [m["id"] for m in reg["models"]]


def find_model(reg, model_id):
    mid = model_id.strip().lower()
    for m in reg["models"]:
        if m["id"] == mid:
            return m
    # tolerant match: allow family display name or example name
    for m in reg["models"]:
        if m["family"].lower() == mid:
            return m
        for ex in m.get("examples", []):
            if ex.lower() == mid:
                return m
    raise SelectionError(
        f"unknown model '{model_id}'. Try one of: {', '.join(list_models(reg))}")


def resolve_gpu(gpu):
    g = gpu.strip().lower()
    g = GPU_ALIASES.get(g, g)
    if g not in GPUS:
        raise SelectionError(
            f"unknown gpu '{gpu}'. Known: {', '.join(GPUS)}")
    return g, GPUS[g]


def normalize_dtype(dtype):
    d = dtype.strip().lower()
    if d not in DTYPES:
        raise SelectionError(
            f"unknown dtype '{dtype}'. Known: {', '.join(sorted(DTYPES))}")
    return DTYPE_NORMALIZE.get(d, d)


# ---------------------------------------------------------------------------
# Compute-dtype resolution: take the *requested* dtype and what the model
# supports, and degrade to the strongest dtype the GPU can actually run.
# Returns (resolved_scheme, note).
# ---------------------------------------------------------------------------
def resolve_compute_dtype(requested, gpu_caps, model):
    supported = set(model["arch"].get("quant", []))
    # "auto": pick the best the model+gpu allow. Prefer fp8 on capable HW for
    # large models, else bf16, else fp16.
    if requested == "auto":
        if "fp8" in supported and gpu_caps["fp8"]:
            return "fp8", "auto: model has FP8 weights and GPU has FP8 tensor cores"
        if gpu_caps["bf16"]:
            return "bf16", "auto: bf16 (broadest tensor-core dtype on this GPU)"
        return "fp16", "auto: fp16 (GPU predates bf16 tensor cores)"

    note = None
    d = requested

    # fp8 family: needs sm89+ tensor cores; else degrade.
    if d in ("fp8", "fp8_e5m2"):
        if not gpu_caps["fp8"]:
            fallback = "bf16" if gpu_caps["bf16"] else "fp16"
            note = (f"FP8 requested but {gpu_caps['name']} (sm{gpu_caps['sm']}) "
                    f"has no FP8 tensor cores -> degrade to {fallback}")
            return fallback, note

    # mxfp4 / fp4: no native FP4 ABI here and only Blackwell has FP4 TCs;
    # model the experts as fp8 on fp8-capable HW, else bf16.
    if d == "mxfp4":
        if gpu_caps["fp8"]:
            return "fp8", ("MXFP4 experts modeled via FP8 compute path "
                           "(no native FP4 on this GPU)")
        fallback = "bf16" if gpu_caps["bf16"] else "fp16"
        return fallback, f"MXFP4 unsupported on sm{gpu_caps['sm']} -> {fallback}"

    # bf16 needs sm80+; T4 degrades to fp16.
    if d == "bf16" and not gpu_caps["bf16"]:
        return "fp16", (f"bf16 requested but sm{gpu_caps['sm']} lacks bf16 "
                        f"tensor cores -> fp16")

    # tf32 is only an Ampere+ F32 path.
    if d == "tf32" and not gpu_caps["tf32"]:
        return "fp16", f"tf32 unsupported on sm{gpu_caps['sm']} -> fp16"

    # w4a16 / w8a8 always OK on sm75+ (all our GPUs).
    return d, note


# Real-world best-in-class backend names for the rationale (the ABI symbol is
# the same; this just names *why* it's strongest on that arch/dtype).
def gemm_backend_name(scheme, gpu_caps):
    sm = gpu_caps["sm"]
    if scheme == "fp8":
        return "DeepGEMM" if sm >= 90 else "TransformerEngine/cuBLASLt FP8"
    if scheme == "w4a16":
        return "Machete (WGMMA)" if sm >= 90 else "Marlin"
    if scheme == "w8a8":
        return "CUTLASS INT8 (SmoothQuant)"
    if scheme in ("bf16", "fp16"):
        return "cuBLASLt / CUTLASS"
    if scheme in ("tf32", "f32"):
        return "CUTLASS TF32"
    return "cuBLASLt"


def attn_backend_name(gpu_caps, mla=False, decode=False):
    sm = gpu_caps["sm"]
    if mla:
        return "FlashMLA" if sm >= 90 else "FlashInfer MLA"
    if decode:
        return "FlashInfer paged decode"
    return "FlashAttention-3" if sm >= 90 else "FlashAttention-2"


# Which logical ops are GEMM-shaped (so they honor the weight-quant scheme).
GEMM_OPS = {"qkv_proj", "o_proj", "mlp_gate_up", "mlp_down", "lm_head",
            "moe_grouped_gemm"}
DENSE_GEMM_OPS = GEMM_OPS - {"moe_grouped_gemm"}
# Ops that always stay in the model's activation dtype (norms, rope, act, etc).
ACT_DTYPE_OPS = {"attn_norm", "ffn_norm", "rope", "mlp_act", "embedding",
                 "attn_prefill", "attn_decode", "attn_backward"}


def _pick_gemm_fn(op, scheme, default_fn):
    """Choose the quant-aware GEMM ABI symbol for a GEMM-shaped op."""
    if op == "moe_grouped_gemm":
        # grouped path has a single ABI symbol; dtype carries the quant info
        return "ks_moe_grouped_gemm"
    if scheme == "w4a16":
        return "ks_gemm_w4a16"
    if scheme == "w8a8":
        return "ks_gemm_w8a8"
    # fp8/bf16/fp16/tf32 dense GEMM. Use the bias+act fused epilogue for the
    # gate/up MLP projection (fuses SwiGLU's act when packed); plain ks_gemm
    # for the rest. We keep ks_gemm as the canonical symbol so the table stays
    # readable, but record fused availability in the note.
    return default_fn if default_fn else "ks_gemm"


def select(model_id, gpu, dtype, mode="inference", reg=None):
    """Return the full per-op plan dict."""
    reg = reg or load_registry()
    model = find_model(reg, model_id)
    gkey, gcaps = resolve_gpu(gpu)
    requested = normalize_dtype(dtype)
    scheme, dnote = resolve_compute_dtype(requested, gcaps, model)

    arch = model["arch"]
    is_mla = arch["attention"] == "MLA"
    is_moe = arch["mlp"]["type"] == "MoE"
    attn = arch["attention"]
    act_ks_dtype = KS_DTYPE.get(
        "bf16" if scheme in ("w4a16", "w8a8", "fp8", "fp8_e5m2", "mxfp4")
        and gcaps["bf16"] else
        ("fp16" if scheme in ("w4a16", "w8a8", "fp8", "fp8_e5m2", "mxfp4")
         else scheme), "KS_DTYPE_BF16")
    gemm_ks_dtype = KS_DTYPE.get(scheme, "KS_DTYPE_BF16")

    ops = list(reg["logical_ops"])
    if mode == "training":
        # Training is forward-prefill + backward; decode-time ops don't apply.
        ops = [o for o in ops if o not in ("attn_decode", "sampling")]
        ops = ops + list(reg["training_ops"])

    plan = {}
    base_ops = model["ops"]

    for op in ops:
        entry = build_op(op, model, base_ops, scheme, gcaps,
                         act_ks_dtype, gemm_ks_dtype, is_mla, is_moe, attn, mode)
        if entry is not None:
            # Annotate with the optimal external provider from the Cartesian
            # table (single source of truth). The kernel-set C-ABI `fn` remains
            # the portable entry point; `optimal_provider`/`optimal_source` name
            # the industry-best runtime backend dispatch would pick on this arch.
            cell = optimal_cell(op, gcaps["sm"], scheme)
            if cell is not None:
                entry["optimal_provider"] = cell["provider"]
                entry["optimal_source"] = cell["source"]
                if cell["source"] == "measured":
                    entry["optimal_metric"] = cell.get("metric")
            plan[op] = entry

    return {
        "model": model["id"],
        "family": model["family"],
        "gpu": gcaps["name"],
        "gpu_key": gkey,
        "sm": gcaps["sm"],
        "arch_summary": arch_summary(arch),
        "requested_dtype": dtype,
        "resolved_scheme": scheme,
        "dtype_note": dnote,
        "mode": mode,
        "ops": plan,
    }


def build_op(op, model, base_ops, scheme, gcaps, act_dt, gemm_dt,
             is_mla, is_moe, attn, mode):
    sm = gcaps["sm"]

    # --- training-only ops -------------------------------------------------
    if op == "attn_backward":
        return mk("ks_flash_attn_backward", act_dt,
                  f"{attn_backend_name(gcaps)} backward (training)")
    if op == "cross_entropy":
        return mk("ks_fused_linear_cross_entropy", "KS_DTYPE_F32",
                  "Liger-style chunked fused-linear-CE (no full-logit materialization)")
    if op == "optimizer":
        return mk("ks_adamw", "KS_DTYPE_F32",
                  "Apex-style fused AdamW; fp32 master weights + state")

    # --- ops that don't exist for this model ------------------------------
    spec = base_ops.get(op)
    if spec is None:
        # moe_* ops only present for MoE models; mlp dense ops still apply.
        return None

    fn = spec["fn"]

    # ---- attention -------------------------------------------------------
    if op == "attn_prefill":
        # MLA prefill still uses flash on up-projected q/k/v.
        return mk("ks_flash_attn_varlen", act_dt,
                  f"{attn_backend_name(gcaps)} varlen prefill"
                  + (" (FP8 path)" if scheme in ("fp8",) and sm >= 90 else "")
                  + grouping_note(model["arch"]))
    if op == "attn_decode":
        if is_mla:
            return mk("ks_mla_decode", act_dt,
                      f"{attn_backend_name(gcaps, mla=True)} over compressed "
                      f"latent KV (rank "
                      f"{kv_lora(model)})")
        return mk("ks_paged_attn_decode", act_dt,
                  f"{attn_backend_name(gcaps, decode=True)}"
                  + grouping_note(model["arch"]))

    # ---- norms -----------------------------------------------------------
    if op in ("attn_norm", "ffn_norm"):
        if fn == "ks_layer_norm":
            return mk("ks_layer_norm", act_dt,
                      "LayerNorm (fp32 accumulate)")
        # RMSNorm: prefer the fused add-residual variant between sublayers.
        backend = "Liger" if mode == "training" else "FlashInfer/vLLM"
        return mk("ks_rms_norm_residual", act_dt,
                  f"{backend} fused add-RMSNorm")

    # ---- rope ------------------------------------------------------------
    if op == "rope":
        interleaved = (model["arch"].get("rope") or {}).get("style") == "gptj"
        conv = "GPT-J interleaved" if interleaved else "NeoX rotate-half"
        rscale = (model["arch"].get("rope") or {}).get("scaling")
        sc = f", {rscale} scaling" if rscale else ""
        return mk("ks_rope_gather", act_dt,
                  f"{conv} RoPE{sc} (fp32 angle math)")

    # ---- embedding / sampling -------------------------------------------
    if op == "embedding":
        return mk("ks_embedding_lookup", act_dt, "embedding gather")
    if op == "sampling":
        return mk("ks_sample", "KS_DTYPE_F32",
                  "FlashInfer-style fused temp+top-k+top-p sampling")

    # ---- MoE gate --------------------------------------------------------
    if op == "moe_gate":
        if fn == "ks_moe_gate_sigmoid_group_topk":
            mlp = model["arch"]["mlp"]
            return mk("ks_moe_gate_sigmoid_group_topk", "KS_DTYPE_F32",
                      f"DeepSeek group-limited aux-loss-free sigmoid gating "
                      f"(top-{mlp.get('top_k')} of {mlp.get('n_experts')}, "
                      f"{mlp.get('n_group')} groups)")
        mlp = model["arch"]["mlp"]
        return mk("ks_moe_gate_softmax_topk", "KS_DTYPE_F32",
                  f"softmax top-{mlp.get('top_k')} of {mlp.get('n_experts')} routing")

    # ---- MoE grouped gemm ------------------------------------------------
    if op == "moe_grouped_gemm":
        be = gemm_backend_name(scheme, gcaps)
        if scheme == "fp8" and sm >= 90:
            be = "DeepGEMM grouped (FP8 block-scaled)"
        elif scheme == "fp8":
            be = "CUTLASS grouped FP8"
        elif scheme in ("bf16", "fp16"):
            be = "Triton fused_moe / CUTLASS grouped"
        return mk("ks_moe_grouped_gemm", gemm_dt,
                  f"{be}; expert weights {scheme}")

    # ---- MLP activation --------------------------------------------------
    if op == "mlp_act":
        if fn == "ks_geglu":
            return mk("ks_geglu", act_dt, "GeGLU (gelu-tanh) gated act")
        if fn == "ks_gelu":
            return mk("ks_gelu", act_dt, "dense GeLU MLP activation")
        be = "Liger" if mode == "training" else "vLLM SiLU-mul"
        fused = (" (fused GEMM+SwiGLU on Hopper FP8)"
                 if scheme == "fp8" and sm >= 90 else "")
        return mk("ks_swiglu", act_dt, f"{be} SwiGLU{fused}")

    # ---- GEMM-shaped ops (qkv/o/gate_up/down/lm_head) -------------------
    if op in GEMM_OPS:
        chosen = _pick_gemm_fn(op, scheme, fn)
        be = gemm_backend_name(scheme, gcaps)
        extra = ""
        if op == "lm_head":
            extra = " (final logits)"
        if op == "mlp_gate_up" and not is_moe:
            extra = " (gate+up; fuse act via ks_gemm_bias_act)"
        return mk(chosen, gemm_dt, f"{be} {scheme} GEMM{extra}")

    # default passthrough
    return mk(fn, act_dt, "")


def mk(fn, ks_dtype, rationale):
    return {"fn": fn, "ks_dtype": ks_dtype, "rationale": rationale}


def grouping_note(arch):
    a = arch["attention"]
    if a == "GQA":
        return f" (GQA: {arch['n_kv_heads']} kv-heads shared by {arch['n_heads']} q-heads)"
    if a == "MQA":
        return f" (MQA: 1 kv-group)"
    if a == "MLA":
        return " (MLA latent KV)"
    return " (MHA)"


def kv_lora(model):
    for e in model["arch"].get("extras", []):
        if e.startswith("kv-lora-rank-"):
            return e.rsplit("-", 1)[-1]
    return "512"


def arch_summary(arch):
    mlp = arch["mlp"]
    if mlp["type"] == "MoE":
        mlp_str = (f"MoE {mlp.get('n_experts')}e/top-{mlp.get('top_k')}"
                   + (f"+{mlp['n_shared']}shared" if mlp.get("n_shared") else "")
                   + f" {mlp.get('gating', 'softmax')}")
    else:
        mlp_str = mlp["type"]
    r = arch.get("rope")
    if r is None:
        rope_str = "ALiBi/none"
    else:
        rope_str = f"{r['style']} theta={r['theta']}"
        if r.get("scaling"):
            rope_str += f"/{r['scaling']}"
    return {
        "attention": arch["attention"],
        "heads": arch["n_heads"],
        "kv_heads": arch["n_kv_heads"],
        "head_dim": arch["head_dim"],
        "hidden": arch["hidden"],
        "vocab": arch["vocab"],
        "norm": arch["norm"],
        "rope": rope_str,
        "mlp": mlp_str,
        "quant": ",".join(arch.get("quant", [])),
    }


if __name__ == "__main__":
    # Smoke test when run directly.
    reg = load_registry()
    for (m, g, d, mode) in [
        ("deepseek-v3", "h100", "fp8", "inference"),
        ("llama-3-8b", "a100", "bf16", "inference"),
        ("mixtral-8x7b", "l4", "w4a16", "inference"),
        ("gemma2-9b", "t4", "bf16", "inference"),
        ("llama-3-70b", "h100", "bf16", "training"),
    ]:
        p = select(m, g, d, mode, reg)
        print(f"\n== {m} on {g} ({d}, {mode}) -> scheme={p['resolved_scheme']}")
        for op, e in p["ops"].items():
            print(f"  {op:18s} {e['fn']:28s} {e['ks_dtype']:16s} {e['rationale']}")
